import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { today, addDays } from '../src/utils.js'
const owner = 'bdfe3c81-3e96-4928-aa91-dc4ebabb7e87'
const now = () => new Date().toISOString()
async function mockWorkspace(page) {
  const data = { projects: [], tasks: [], documents: [], comments: [], activity: [] }
  let failSave = false
  const session = { access_token: 'test-only-token', refresh_token: 'test-only-refresh', token_type: 'bearer', expires_in: 3600, expires_at: Math.floor(Date.now()/1000)+3600, user: { id: owner, email:'test@example.com', aud:'authenticated', role:'authenticated', app_metadata:{},user_metadata:{},created_at:now() } }
  await page.addInitScript(session => localStorage.setItem('prmg-auth-v1',JSON.stringify(session)),session)
  await page.route('https://fgomaujsdblpzxhnnqrg.supabase.co/**', async route => {
    const req = route.request(), url = new URL(req.url())
    const reply = (json,status=200) => route.fulfill({status,contentType:'application/json',body:JSON.stringify(json)})
    if(url.pathname.includes('/rpc/prmg_reorder_task')) {
      if(failSave) return reply({message:'Simulated network save failure'},503)
      const {p_task_id,p_target_id,p_after} = req.postDataJSON()
      const sorted = [...data.tasks].sort((a,b) => a.sort_order == null && b.sort_order == null ? b.created_at.localeCompare(a.created_at) || a.id.localeCompare(b.id) : a.sort_order == null ? -1 : b.sort_order == null ? 1 : a.sort_order-b.sort_order)
      const moved=sorted.find(task=>task.id===p_task_id), rest=sorted.filter(task=>task.id!==p_task_id)
      rest.splice(rest.findIndex(task=>task.id===p_target_id)+(p_after?1:0),0,moved)
      rest.forEach((task,index)=>{task.sort_order=index+1})
      return reply(null)
    }
    if(url.pathname.includes('/rpc/')) return reply(true)
    if(url.pathname.includes('/auth/')) return reply(session)
    const table = url.pathname.split('/').pop().replace('prmg_','')
    if(!data[table]) return reply({message:'Unknown table'},404)
    if(req.method() === 'GET') return reply(data[table])
    if(failSave) return reply({message:'Simulated network save failure'},503)
    const id = url.searchParams.get('id')?.slice(3)
    if(req.method() === 'POST') {
      const row = { id:randomUUID(),created_at:now(),updated_at:now(),...req.postDataJSON() }
      data[table].unshift(row); return reply(row,201)
    }
    const index = data[table].findIndex(r => r.id === id)
    if(req.method() === 'PATCH') { const row = {...data[table][index],...req.postDataJSON(),updated_at:now()}; data[table][index]=row;return reply(row) }
    if(req.method() === 'DELETE') { data[table].splice(index,1); return reply({id}) }
    return reply(null)
  })
  return {data,setFailSave: value => { failSave = value }}
}

test('project, task, subtask, comment, knowledge page and Gantt workflows',async({page}) => {
  const {data,setFailSave} = await mockWorkspace(page)
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('./')
  await expect(page.getByRole('heading',{name:'Projects',exact:true})).toBeVisible()
  await expect(page.locator('.topbar .app-version')).toHaveCount(0)
  await expect(page.locator('.workspace-footer .app-version')).toBeVisible()
  await expect(page.locator('.sidebar').getByRole('button',{name:'Hide navigation',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'New project',exact:true})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Refresh',exact:true})).toHaveCount(0)
  await expect(page.locator('.page-heading p')).toHaveCount(0)
  await expect(page.locator('.view-toolbar > .muted')).toHaveCount(0)
  await page.getByRole('button',{name:'Create project',exact:true}).click()
  await expect(page.getByLabel('Project name')).toHaveValue('')
  await expect(page.locator('[placeholder]')).toHaveCount(0)
  await page.getByLabel('Project name').fill('Website launch')
  await page.getByLabel('Description',{exact:true}).fill('A clear home for our next launch.')
  await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('.card-title').filter({hasText:'Website launch'}).click()
  await expect(page.locator('.back-link')).toHaveCount(0)
  await page.getByRole('button',{name:'Board',exact:true}).click()
  const todo = page.locator('.kanban-column').filter({has: page.getByRole('heading',{name:'To do',exact:true})})
  await todo.getByRole('button',{name:'Add task',exact:true}).click()
  await todo.getByRole('button',{name:'Open full task form'}).click()
  await page.getByLabel('Title',{exact:true}).fill('Build the homepage')
  await page.getByRole('combobox',{name:'Priority',exact:true}).selectOption('high')
  await page.getByLabel('Due date',{exact:true}).fill('2026-10-01')
  await page.getByLabel('New subtask').fill('Write the headline')
  await page.getByRole('button',{name:'Add',exact:true}).click()
  setFailSave(true)
  await page.getByRole('button',{name:'Create task',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Simulated network save failure')
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Build the homepage')
  setFailSave(false)
  await page.getByRole('button',{name:'Create task',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button',{name:'Build the homepage',exact:true}).click()
  await page.getByLabel('Complete Write the headline').check()
  await page.getByLabel('New comment').fill('First draft is ready.')
  await page.getByRole('button',{name:'Post comment'}).click()
  await expect(page.locator('.comment')).toContainText('First draft is ready.')
  await page.getByRole('button',{name:'Save changes',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button',{name:'Complete Build the homepage',exact:true}).click()
  await expect(page.locator('.kanban-column').filter({has:page.getByRole('heading',{name:'Done',exact:true})})).toContainText('Build the homepage')
  await page.locator('.project-tabs').getByRole('button',{name:'Knowledge base'}).click()
  await page.getByRole('button',{name:'New page',exact:true}).click()
  await page.getByLabel('Title',{exact:true}).fill('Launch plan')
  await page.getByRole('combobox',{name:'Category',exact:true}).fill('Plan')
  await page.getByLabel('Content · Markdown supported').fill('## Decisions\n\nA **focused** launch.\n\n<script>alert(1)</script>')
  await page.getByRole('button',{name:'Preview',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Decisions'})).toBeVisible()
  await expect(page.locator('.markdown script')).toHaveCount(0)
  await page.getByRole('button',{name:'Create page',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('.project-tabs').getByRole('button',{name:'Gantt chart'}).click()
  await expect(page.getByRole('region',{name:'Gantt chart',exact:true})).toBeVisible()
  await page.locator('nav').getByRole('button',{name:/^Projects/}).click()
  await page.screenshot({path:'test-results/overview.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('button',{name:'Open navigation'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/mobile.png',fullPage:true,animations:'disabled'})
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('button',{name:'Workspace settings',exact:true}).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button',{name:'Export workspace',exact:true}).click()
  expect((await download).suggestedFilename()).toMatch(/^prmg-backup/)
  expect(data.projects).toHaveLength(1);expect(data.tasks[0].status).toBe('done');expect(data.tasks[0].checklist[0].done).toBe(true)
  expect(data.documents).toHaveLength(1);expect(data.comments).toHaveLength(1)
  expect(errors).toEqual([])
})

test('login is required and invalid credentials do not unlock workspace',async({page})=>{
  await page.route('**/auth/v1/token*',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'invalid_grant',error_description:'Invalid login credentials'})}))
  await page.goto('./')
  await expect(page.getByRole('heading',{name:/Good work starts/})).toBeVisible()
  await page.getByLabel('Passcode',{exact:true}).fill('not-a-real-password')
  await page.getByRole('button',{name:'Open your workspace'}).click()
  await expect(page.getByRole('alert')).toContainText('didn’t match')
  await expect(page.getByRole('heading',{name:'Projects',exact:true})).toHaveCount(0)
  await page.screenshot({path:'test-results/login.png',fullPage:true})
})

test('expired session returns to locked login',async({page})=>{
  await mockWorkspace(page)
  await page.route('**/rpc/prmg_session_valid',route=>route.fulfill({contentType:'application/json',body:'false'}))
  await page.goto('./')
  await expect(page.getByRole('heading',{name:/Good work starts/})).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('expired')
})

test('inline tasks save in their column and preserve drafts on errors and in the full form', async ({page}) => {
  const {data, setFailSave} = await mockWorkspace(page)
  data.projects.push({id: randomUUID(), name: 'Quick tasks', status: 'active', color: '#426951', created_at: now(), updated_at: now()})
  await page.goto('./')
  await page.locator('.card-title').filter({hasText: 'Quick tasks'}).click()
  await page.getByRole('button',{name:'Board',exact:true}).click()
  const column = page.locator('.kanban-column').filter({has: page.getByRole('heading', {name: 'In progress', exact: true})})
  await column.getByRole('button', {name: 'Add task', exact: true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const title = column.getByRole('textbox', {name: 'Title', exact: true})
  await expect(title).toBeFocused()
  await expect(column.locator('form').getByRole('button', {name: 'Add task', exact: true})).toHaveCount(0)
  await expect(column.locator('form').getByText('Title', {exact:true})).toHaveCount(0)
  await expect(column.locator('form').getByText('Open full task form', {exact:true})).toHaveCount(0)
  await title.press('Enter')
  expect(data.tasks).toHaveLength(0)
  await title.fill('  Quick draft  ')
  setFailSave(true)
  await title.press('Enter')
  await expect(column.getByRole('alert')).toContainText('Simulated network save failure')
  await expect(title).toHaveValue('  Quick draft  ')
  setFailSave(false)
  await title.press('Enter')
  await expect(column.getByRole('button', {name: 'Quick draft', exact: true})).toBeVisible()
  expect(data.tasks).toHaveLength(1)
  expect(data.tasks[0]).toMatchObject({title: 'Quick draft', status: 'in_progress', project_id: data.projects[0].id})
  await column.getByRole('button', {name: 'Add task to In progress', exact: true}).click()
  await title.fill('More details')
  await column.getByRole('button', {name: 'Open full task form'}).click()
  await expect(page.getByRole('dialog').getByLabel('Title', {exact: true})).toHaveValue('More details')
  await expect(page.getByRole('dialog').getByRole('combobox', {name: 'Status', exact: true})).toHaveValue('in_progress')
  await expect(page.getByRole('dialog').getByRole('combobox', {name: 'Project', exact: true})).toHaveValue(data.projects[0].id)
  await page.getByRole('button', {name: 'Close dialog'}).click()
  await expect(title).toHaveCount(0)
  await column.getByRole('button', {name: 'Add task', exact: true}).click()
  await title.fill('Discard this draft')
  await expect(column.getByRole('button', {name: 'Cancel', exact: true})).toHaveCount(0)
  await title.press('Escape')
  await expect(title).toHaveCount(0)
  expect(data.tasks).toHaveLength(1)
})

test('All Projects combines tasks and grouped Gantt schedules with readable project navigation', async ({page}) => {
  const {data} = await mockWorkspace(page)
  const names = ['Book Club at Beth David Community Center', 'Hebrew Class at Beth David Congregation', 'Archived reading group']
  data.projects.push(...names.map((name, index) => ({id: randomUUID(), name, status: index === 2 ? 'archived' : 'active', color: ['#49755f','#6883b3','#9474af'][index], created_at: now(), updated_at: now()})))
  data.tasks.push(...data.projects.map((project, index) => ({id: randomUUID(), project_id: project.id, title: ['Choose the next book','Prepare the lesson','Reading notes'][index], status: index === 0 ? 'done' : 'todo', priority: 'medium', start_date: index === 2 ? null : today(), due_date: index === 2 ? null : addDays(today(), 4), checklist: [], labels: [], created_at: now(), updated_at: now()})))
  await page.setViewportSize({width: 1440, height: 1000})
  await page.goto('./')
  const expandedWidth = (await page.locator('.main-shell').boundingBox()).width
  await page.getByRole('button', {name: 'Hide navigation', exact: true}).click()
  await expect(page.locator('.sidebar')).toBeHidden()
  await expect(page.getByRole('button', {name: 'Open navigation', exact: true})).toHaveAttribute('aria-expanded', 'false')
  expect((await page.locator('.main-shell').boundingBox()).width).toBeGreaterThan(expandedWidth)
  await page.getByRole('button', {name: 'Open navigation', exact: true}).click()
  await expect(page.locator('.sidebar')).toBeVisible()
  await expect(page.locator('.sidebar-projects > button').first()).toHaveText('All Projects')
  const projectLabel = page.locator('.sidebar-project span').filter({hasText: names[0]})
  expect(await projectLabel.evaluate(node => getComputedStyle(node).whiteSpace)).toBe('normal')
  expect((await page.locator('.sidebar').boundingBox()).width).toBeGreaterThanOrEqual(330)
  await page.locator('.sidebar-projects').getByRole('button', {name: 'All Projects', exact: true}).click()
  await expect(page.getByRole('heading', {name: 'All Projects', exact: true})).toBeVisible()
  await expect(page.getByRole('button', {name: 'New task', exact: true})).toHaveCount(0)
  for(const task of data.tasks) await expect(page.getByRole('button', {name: task.title, exact: true})).toBeVisible()
  await page.locator('.project-tabs').getByRole('button', {name: 'Gantt chart', exact: true}).click()
  await page.getByRole('button', {name: 'Fit schedule', exact: true}).click()
  await expect(page.locator('.gantt-group')).toHaveCount(3)
  const taskIndent = await page.locator('.gantt-row:not(.gantt-summary) .gantt-label').first().evaluate(node => parseInt(getComputedStyle(node).paddingLeft))
  expect(taskIndent).toBeGreaterThanOrEqual(68)
  await expect(page.locator('.gantt-summary').first()).toContainText('100% complete')
  await expect(page.locator('.gantt-row').filter({hasText: 'Reading notes'})).toContainText('Add dates to schedule')
  const chart = page.getByRole('region', {name: 'Gantt chart', exact: true})
  const bar = chart.getByRole('button', {name: 'Edit Choose the next book', exact: true})
  expect((await bar.boundingBox()).width).toBe(180)
  await page.screenshot({path:'test-results/gantt-desktop.png', fullPage:true})
  await chart.getByRole('button', {name: `Collapse ${names[0]}`, exact:true}).click()
  await expect(bar).toHaveCount(0)
  await chart.getByRole('button', {name: `Expand ${names[0]}`, exact:true}).click()
  await bar.click()
  await expect(page.getByRole('dialog').getByLabel('Title', {exact:true})).toHaveValue('Choose the next book')
  await page.getByRole('button', {name:'Close dialog'}).click()
  await page.getByRole('button', {name:'Next period', exact:true}).click()
  await expect(chart.getByText('Outside this period').first()).toBeVisible()
  await page.getByRole('button', {name:'Fit schedule', exact:true}).click()
  await page.setViewportSize({width:390, height:844})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/gantt-mobile.png', fullPage:true, animations:'disabled'})
  await page.getByRole('button', {name:'Open navigation'}).click()
  await page.getByRole('button', {name:'Hide navigation', exact:true}).click()
  await expect(page.locator('.sidebar')).toBeHidden()
  await page.getByRole('button', {name:'Open navigation', exact:true}).click()
  await page.locator('.sidebar-projects').getByRole('button', {name:names[1], exact:true}).click()
  await expect(page.getByRole('heading', {name:names[1], exact:true})).toBeVisible()
  await expect(page.getByRole('button', {name:'Prepare the lesson', exact:true})).toBeVisible()
  await expect(page.getByRole('button', {name:'Choose the next book', exact:true})).toHaveCount(0)
  await page.locator('.project-tabs').getByRole('button', {name:'Gantt chart', exact:true}).click()
  await expect(page.locator('.gantt-group')).toHaveCount(1)
})

test('Gantt dragging reschedules titles and bars, preserves duration, and handles failed saves', async ({page}) => {
  const {data, setFailSave} = await mockWorkspace(page)
  const project = {id: randomUUID(), name: 'Schedule changes', status: 'active', color: '#49755f', created_at: now(), updated_at: now()}
  data.projects.push(project)
  data.tasks.push({id:randomUUID(), project_id:project.id, title:'Move this task', status:'todo', priority:'medium', start_date:today(), due_date:addDays(today(),4), checklist:[], labels:[], created_at:now(), updated_at:now()}, {id:randomUUID(), project_id:project.id, title:'Undated task', status:'todo', priority:'medium', start_date:null, due_date:null, checklist:[], labels:[], created_at:now(), updated_at:now()})
  await page.setViewportSize({width:1600,height:1000})
  await page.goto('./')
  await page.locator('nav').getByRole('button',{name:'Gantt chart',exact:true}).click()
  const row = page.locator('.gantt-row:not(.gantt-summary)').filter({hasText:'Move this task'})
  const title = row.locator('.gantt-name')
  const lane = row.locator('.gantt-lane')
  await title.dragTo(lane,{targetPosition:{x:6 * 36 + 18,y:50}})
  await expect.poll(() => data.tasks[0].start_date).toBe(addDays(today(),3))
  expect(data.tasks[0].due_date).toBe(addDays(today(),7))
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await row.locator('.gantt-bar').dragTo(lane,{sourcePosition:{x:18,y:12},targetPosition:{x:8 * 36 + 18,y:50}})
  await expect.poll(() => data.tasks[0].start_date).toBe(addDays(today(),5))
  expect(data.tasks[0].due_date).toBe(addDays(today(),9))
  setFailSave(true)
  await title.dragTo(lane,{targetPosition:{x:3 * 36 + 18,y:50}})
  await expect(page.getByRole('alert')).toContainText('Could not move Move this task')
  expect(data.tasks[0].start_date).toBe(addDays(today(),5))
  expect(data.tasks[0].due_date).toBe(addDays(today(),9))
  setFailSave(false)
  await title.focus()
  await title.press('Alt+ArrowLeft')
  await expect.poll(() => data.tasks[0].start_date).toBe(addDays(today(),4))
  expect(data.tasks[0].due_date).toBe(addDays(today(),8))
  const undated = page.locator('.gantt-row:not(.gantt-summary)').filter({hasText:'Undated task'})
  await undated.locator('.gantt-name').dragTo(undated.locator('.gantt-lane'),{targetPosition:{x:4 * 36 + 18,y:50}})
  await expect.poll(() => data.tasks[1].start_date).toBe(addDays(today(),1))
  expect(data.tasks[1].due_date).toBe(addDays(today(),1))
  await title.click()
  await expect(page.getByRole('dialog').getByLabel('Title',{exact:true})).toHaveValue('Move this task')
})

test('Gantt task balloons show complete long names on short bars', async ({page}) => {
  const {data} = await mockWorkspace(page)
  data.projects.push({id:randomUUID(), name:'Reading group', status:'active', color:'#49755f', created_at:now(), updated_at:now()})
  const title = 'Look at possible books for the next community reading group and prepare discussion questions for everyone'
  data.tasks.push({id:randomUUID(), project_id:data.projects[0].id, title, status:'todo', priority:'medium', start_date:today(), due_date:today(), checklist:[], labels:[], created_at:now(), updated_at:now()})
  await page.goto('./')
  await page.locator('nav').getByRole('button',{name:'Gantt chart',exact:true}).click()
  const balloon = page.locator('.gantt-task-balloon')
  await expect(balloon).toHaveText(title)
  await expect(balloon).toBeVisible()
  expect(await balloon.evaluate(node => { const range = document.createRange(); range.selectNodeContents(node); const text = range.getBoundingClientRect(), balloon = node.getBoundingClientRect(); return text.left >= balloon.left && text.right <= balloon.right && text.top >= balloon.top && text.bottom <= balloon.bottom })).toBe(true)
  const row = page.locator('.gantt-row:not(.gantt-summary)')
  expect((await balloon.boundingBox()).width).toBeGreaterThan((await row.locator('.gantt-bar').boundingBox()).width)
  const taskTitle = await row.locator('.gantt-title-text').boundingBox()
  const taskBar = await row.locator('.gantt-bar').boundingBox()
  expect(Math.abs(taskBar.y + taskBar.height / 2 - (taskTitle.y + 11))).toBeLessThanOrEqual(1)
  await balloon.dragTo(row.locator('.gantt-lane'),{targetPosition:{x:4 * 36 + 18,y:90}})
  await expect.poll(() => data.tasks[0].start_date).toBe(addDays(today(),1))
  expect(data.tasks[0].due_date).toBe(addDays(today(),1))
  await page.screenshot({path:'test-results/gantt-balloon.png',fullPage:true})
  await balloon.click()
  await expect(page.getByRole('dialog').getByLabel('Title',{exact:true})).toHaveValue(title)
})

test('list layout adds tasks in empty and populated lists and respects the project filter', async ({page}) => {
  const {data} = await mockWorkspace(page)
  data.projects.push(...['First project','Second project'].map(name => ({id:randomUUID(),name,status:'active',color:'#49755f',created_at:now(),updated_at:now()})))
  await page.goto('./')
  await page.locator('nav').getByRole('button',{name:'Tasks',exact:true}).click()
  await page.getByRole('button',{name:'List',exact:true}).click()
  await page.getByRole('combobox',{name:'Filter project',exact:true}).selectOption(data.projects[1].id)
  const add = page.getByRole('button',{name:'Add task',exact:true})
  await add.click()
  const title = page.locator('.list-task-entry').getByRole('textbox',{name:'Title',exact:true})
  await expect(title).toBeFocused()
  await expect(title).toHaveValue('')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await title.fill('First list task')
  await title.press('Enter')
  await expect(page.locator('.task-list')).toContainText('First list task')
  expect(data.tasks[0]).toMatchObject({project_id:data.projects[1].id,status:'todo'})
  await add.click()
  await title.fill('Second list task')
  await title.press('Enter')
  await expect(page.locator('.task-list .task-row')).toHaveCount(2)
  await add.click()
  await title.fill('Detailed list task')
  await page.locator('.list-task-entry').getByRole('button',{name:'Open full task form'}).click()
  await expect(page.getByRole('dialog').getByLabel('Title',{exact:true})).toHaveValue('Detailed list task')
  await expect(page.getByRole('dialog').getByRole('combobox',{name:'Project',exact:true})).toHaveValue(data.projects[1].id)
})

test('list is the default and drag ordering persists, including filtered moves and failed saves', async ({page}) => {
  const {data,setFailSave} = await mockWorkspace(page)
  data.projects.push(...['One','Two'].map(name=>({id:randomUUID(),name,status:'active',color:'#49755f',created_at:now(),updated_at:now()})))
  data.tasks.push(...['First','Hidden','Last'].map((title,index)=>({id:randomUUID(),project_id:data.projects[index===1?1:0].id,title,status:'todo',priority:'medium',labels:[],checklist:[],sort_order:index+1,created_at:now(),updated_at:now()})))
  await page.goto('./')
  await page.locator('nav').getByRole('button',{name:'Tasks',exact:true}).click()
  await expect(page.getByRole('button',{name:'List',exact:true})).toHaveClass('selected')
  const titles = page.locator('.task-list .task-title')
  await expect(titles).toHaveText(['First','Hidden','Last'])
  const row = title => page.locator('.list-order-row').filter({has:page.getByRole('button',{name:title,exact:true})})
  await row('Last').dragTo(row('First'),{targetPosition:{x:150,y:5}})
  await expect(titles).toHaveText(['Last','First','Hidden'])
  await page.reload()
  await page.locator('nav').getByRole('button',{name:'Tasks',exact:true}).click()
  await expect(titles).toHaveText(['Last','First','Hidden'])
  await page.getByRole('combobox',{name:'Filter project',exact:true}).selectOption(data.projects[0].id)
  const handle = page.getByRole('button',{name:'Reorder Last',exact:true})
  const from=await handle.boundingBox(), to=await row('First').boundingBox()
  await page.mouse.move(from.x+from.width/2,from.y+from.height/2)
  await page.mouse.down()
  await page.mouse.move(to.x+100,to.y+to.height-5,{steps:8})
  await page.mouse.up()
  await expect(titles).toHaveText(['First','Last'])
  expect(data.tasks.find(t=>t.title==='Hidden').project_id).toBe(data.projects[1].id)
  setFailSave(true)
  await row('Last').dragTo(row('First'),{targetPosition:{x:150,y:5}})
  await expect(page.getByRole('alert')).toContainText('Could not save task order')
  await expect(titles).toHaveText(['First','Last'])
  setFailSave(false)
  await page.getByRole('button',{name:'Reorder Last',exact:true}).press('Alt+ArrowUp')
  await expect(titles).toHaveText(['Last','First'])
  const touchHandle = await page.getByRole('button',{name:'Reorder Last',exact:true}).boundingBox()
  const touchTarget = await row('First').boundingBox()
  const client = await page.context().newCDPSession(page)
  await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchHandle.x+15,y:touchHandle.y+15}]})
  await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchTarget.x+100,y:touchTarget.y+touchTarget.height-5}]})
  await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
  await expect(titles).toHaveText(['First','Last'])
  await client.detach()
  await page.screenshot({path:'test-results/list-ordering.png',fullPage:true})
  await page.getByRole('combobox',{name:'Sort tasks',exact:true}).selectOption('due')
  await expect(page.getByRole('button',{name:'Reorder Last',exact:true})).toBeDisabled()
  await page.getByRole('button',{name:'First',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
})

test('blank opening and persistent task entry with date and status', async ({page}) => {
  const {data, setFailSave} = await mockWorkspace(page)
  data.projects.push({id:randomUUID(), name:'Test project', status:'active', color:'#426951', description:'', created_at:now(), updated_at:now()})
  await page.goto('./')
  await expect(page.locator('.sidebar-version')).toBeVisible()
  await expect(page.locator('.main-content')).toBeEmpty()
  await expect(page.locator('.main-content')).toHaveCSS('background-color','rgb(255, 255, 255)')
  await expect(page.locator('.sidebar-projects-heading')).toHaveText('')
  await page.locator('.sidebar-project').filter({hasText:'Test project'}).click()
  const entry = page.locator('.inline-task')
  await expect(entry.getByLabel('Title',{exact:true})).toHaveValue('')
  await expect(entry.getByLabel('Start date',{exact:true})).toHaveValue(today())
  await expect(entry.getByLabel('End date',{exact:true})).toHaveValue(today())
  await expect(entry.getByLabel('Title',{exact:true})).toBeFocused()
  await expect(page.locator('.project-tabs button')).toHaveText(['Tasks','Gantt chart','Knowledge base'])
  const controls = await entry.locator('.inline-task-entry').evaluate(row => [...row.children].map(control => control.getBoundingClientRect().bottom))
  expect(Math.max(...controls) - Math.min(...controls)).toBeLessThan(12)
  for (const selector of ['body', '.sidebar', '.topbar']) await expect(page.locator(selector)).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(entry.getByText('Project',{exact:true})).toHaveCount(0)
  await entry.getByLabel('Title',{exact:true}).fill('Plan the event')
  await entry.getByLabel('Start date',{exact:true}).fill('2026-10-01')
  await entry.getByLabel('End date',{exact:true}).fill('2026-10-10')
  await entry.getByLabel('Status',{exact:true}).selectOption('in_progress')
  setFailSave(true)
  await entry.getByLabel('Title',{exact:true}).press('Enter')
  await expect(entry.getByRole('alert')).toContainText('Simulated network save failure')
  await expect(entry.getByLabel('Title',{exact:true})).toHaveValue('Plan the event')
  setFailSave(false)
  await entry.getByLabel('Title',{exact:true}).press('Enter')
  await expect(page.locator('.task-row')).toContainText('Plan the event')
  await expect(entry.getByLabel('Title',{exact:true})).toHaveValue('')
  await expect(entry.getByLabel('Start date',{exact:true})).toHaveValue(today())
  await expect(entry.getByLabel('End date',{exact:true})).toHaveValue(today())
  await expect(entry.getByLabel('Title',{exact:true})).toBeFocused()
  expect(data.tasks[0]).toMatchObject({start_date:'2026-10-01',due_date:'2026-10-10',status:'in_progress',project_id:data.projects[0].id})
  expect(await page.locator('.task-list').evaluate(list => !!(list.compareDocumentPosition(document.querySelector('.list-task-entry')) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
  await expect(page.locator('.task-row .project-name, .task-row .badge.medium')).toHaveCount(0)
  await page.getByRole('button',{name:'Board',exact:true}).click()
  await expect(page.locator('.inline-task')).toHaveCount(4)
  await expect(page.getByRole('button',{name:'Add task',exact:true})).toHaveCount(0)
  await page.locator('.project-tabs').getByRole('button',{name:'Gantt chart'}).click()
  for (const days of ['120','150']) {
    await page.getByLabel('Gantt chart period').selectOption(days)
    await expect(page.getByLabel('Gantt chart period')).toHaveValue(days)
  }
  expect(await page.locator('.gantt-row:not(.gantt-summary) .gantt-name').first().evaluate(name => getComputedStyle(name,'::before').content)).toBe('none')
})

test('Gantt endpoints resize independently and weekdays align with dates', async ({page}) => {
  const {data,setFailSave} = await mockWorkspace(page)
  const project = {id:randomUUID(),name:'Resize schedule',status:'active',color:'#49755f',created_at:now(),updated_at:now()}
  data.projects.push(project)
  data.tasks.push({id:randomUUID(),project_id:project.id,title:'Resize task',status:'todo',priority:'medium',start_date:today(),due_date:addDays(today(),4),checklist:[],labels:[],created_at:now(),updated_at:now()})
  await page.setViewportSize({width:1600,height:1000})
  await page.goto('./')
  await page.locator('nav').getByRole('button',{name:'Gantt chart',exact:true}).click()
  await expect(page.locator('.gantt-weekdays span')).toHaveCount(30)
  await expect(page.locator('.gantt-weekdays span').nth(3)).toHaveText('SMTWTFS'[new Date(today()+'T12:00:00').getDay()])
  const start = page.getByRole('button',{name:'Change start date for Resize task',exact:true})
  const end = page.getByRole('button',{name:'Change end date for Resize task',exact:true})
  async function resize(handle, days) {
    const rect = await handle.boundingBox()
    await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2)
    await page.mouse.down()
    await page.mouse.move(rect.x+rect.width/2+days*36,rect.y+rect.height/2,{steps:5})
    await page.mouse.up()
  }
  await resize(end,2)
  await expect.poll(()=>data.tasks[0].due_date).toBe(addDays(today(),6))
  expect(data.tasks[0].start_date).toBe(today())
  await resize(start,1)
  await expect.poll(()=>data.tasks[0].start_date).toBe(addDays(today(),1))
  expect(data.tasks[0].due_date).toBe(addDays(today(),6))
  await resize(start,-2)
  await expect.poll(()=>data.tasks[0].start_date).toBe(addDays(today(),-1))
  await resize(end,-2)
  await expect.poll(()=>data.tasks[0].due_date).toBe(addDays(today(),4))
  setFailSave(true)
  await resize(end,1)
  await expect(page.getByRole('alert')).toContainText('Could not resize Resize task')
  expect(data.tasks[0].due_date).toBe(addDays(today(),4))
  setFailSave(false)
  await resize(end,-8)
  await expect.poll(()=>data.tasks[0].due_date).toBe(addDays(today(),-1))
  await end.focus()
  await end.press('ArrowRight')
  await expect.poll(()=>data.tasks[0].due_date).toBe(today())
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
