import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'
const owner = 'bdfe3c81-3e96-4928-aa91-dc4ebabb7e87'
const now = () => new Date().toISOString()
async function mockWorkspace(page) {
  const data = { projects: [], tasks: [], documents: [], milestones: [], comments: [], activity: [] }
  let failSave = false
  const session = { access_token: 'test-only-token', refresh_token: 'test-only-refresh', token_type: 'bearer', expires_in: 3600, expires_at: Math.floor(Date.now()/1000)+3600, user: { id: owner, email:'test@example.com', aud:'authenticated', role:'authenticated', app_metadata:{},user_metadata:{},created_at:now() } }
  await page.addInitScript(session => localStorage.setItem('prmg-auth-v1',JSON.stringify(session)),session)
  await page.route('https://fgomaujsdblpzxhnnqrg.supabase.co/**', async route => {
    const req = route.request(), url = new URL(req.url())
    const reply = (json,status=200) => route.fulfill({status,contentType:'application/json',body:JSON.stringify(json)})
    if(url.pathname.includes('/rpc/')) return reply(true)
    if(url.pathname.includes('/auth/')) return reply(session)
    const table = url.pathname.split('/').pop().replace('prmg_','')
    if(!data[table]) return reply({message:'Unknown table'},404)
    if(req.method() === 'GET') return reply(data[table])
    if(failSave) return reply({message:'Simulated network save failure'},503)
    const id = url.searchParams.get('id')?.slice(3)
    if(req.method() === 'POST') {
      const row = { id:randomUUID(),created_at:now(),updated_at:now(),...req.postDataJSON() }
      data[table].unshift(row); return reply(row,201)
    }
    const index = data[table].findIndex(r => r.id === id)
    if(req.method() === 'PATCH') { const row = {...data[table][index],...req.postDataJSON(),updated_at:now()}; data[table][index]=row;return reply(row) }
    if(req.method() === 'DELETE') { data[table].splice(index,1); return reply({id}) }
    return reply(null)
  })
  return {data,setFailSave: value => { failSave = value }}
}

test('project, task, subtask, comment, knowledge page and milestone workflows',async({page}) => {
  const {data,setFailSave} = await mockWorkspace(page)
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('./')
  await expect(page.getByRole('heading',{name:'Projects',exact:true})).toBeVisible()
  await page.locator('.page-heading').getByRole('button',{name:'New project',exact:true}).click()
  await page.getByLabel('Project name').fill('Website launch')
  await page.getByLabel('Description',{exact:true}).fill('A clear home for our next launch.')
  await page.getByRole('dialog').getByRole('button',{name:'Create project',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('.card-title').filter({hasText:'Website launch'}).click()
  await page.getByRole('button',{name:'New task',exact:true}).click()
  await page.getByLabel('Title',{exact:true}).fill('Build the homepage')
  await page.getByRole('combobox',{name:'Priority',exact:true}).selectOption('high')
  await page.getByLabel('Due date',{exact:true}).fill('2026-10-01')
  await page.getByLabel('New subtask').fill('Write the headline')
  await page.getByRole('button',{name:'Add',exact:true}).click()
  setFailSave(true)
  await page.getByRole('button',{name:'Create task',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Simulated network save failure')
  await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Build the homepage')
  setFailSave(false)
  await page.getByRole('button',{name:'Create task',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button',{name:'Build the homepage',exact:true}).click()
  await page.getByLabel('Complete Write the headline').check()
  await page.getByLabel('New comment').fill('First draft is ready.')
  await page.getByRole('button',{name:'Post comment'}).click()
  await expect(page.locator('.comment')).toContainText('First draft is ready.')
  await page.getByRole('button',{name:'Save changes',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button',{name:'Complete Build the homepage',exact:true}).click()
  await expect(page.locator('.kanban-column').filter({has:page.getByRole('heading',{name:'Done',exact:true})})).toContainText('Build the homepage')
  await page.locator('.project-tabs').getByRole('button',{name:'Knowledge base'}).click()
  await page.getByRole('button',{name:'New page',exact:true}).click()
  await page.getByLabel('Title',{exact:true}).fill('Launch plan')
  await page.getByLabel('Content · Markdown supported').fill('## Decisions\n\nA **focused** launch.\n\n<script>alert(1)</script>')
  await page.getByRole('button',{name:'Preview',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Decisions'})).toBeVisible()
  await expect(page.locator('.markdown script')).toHaveCount(0)
  await page.getByRole('button',{name:'Create page',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('.project-tabs').getByRole('button',{name:'Timeline'}).click()
  await page.getByRole('button',{name:'New milestone',exact:true}).first().click()
  await page.getByLabel('Title',{exact:true}).fill('Launch day')
  await page.getByRole('button',{name:'Create milestone',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.milestone-list')).toContainText('Launch day')
  await page.getByRole('button',{name:'Complete Launch day',exact:true}).click()
  await expect(page.getByRole('button',{name:'Reopen Launch day',exact:true})).toBeVisible()
  await page.locator('nav').getByRole('button',{name:/^Projects/}).click()
  await page.screenshot({path:'test-results/overview.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('button',{name:'Open navigation'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/mobile.png',fullPage:true,animations:'disabled'})
  await page.getByRole('button',{name:'Open navigation'}).click()
  await page.getByRole('button',{name:'Workspace settings',exact:true}).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button',{name:'Export workspace',exact:true}).click()
  expect((await download).suggestedFilename()).toMatch(/^prmg-backup/)
  expect(data.projects).toHaveLength(1);expect(data.tasks[0].status).toBe('done');expect(data.tasks[0].checklist[0].done).toBe(true)
  expect(data.documents).toHaveLength(1);expect(data.milestones[0].completed).toBe(true);expect(data.comments).toHaveLength(1)
  expect(errors).toEqual([])
})

test('login is required and invalid credentials do not unlock workspace',async({page})=>{
  await page.route('**/auth/v1/token*',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'invalid_grant',error_description:'Invalid login credentials'})}))
  await page.goto('./')
  await expect(page.getByRole('heading',{name:/Good work starts/})).toBeVisible()
  await page.getByLabel('Passcode',{exact:true}).fill('not-a-real-password')
  await page.getByRole('button',{name:'Open your workspace'}).click()
  await expect(page.getByRole('alert')).toContainText('didn’t match')
  await expect(page.getByRole('heading',{name:'Projects',exact:true})).toHaveCount(0)
  await page.screenshot({path:'test-results/login.png',fullPage:true})
})

test('expired session returns to locked login',async({page})=>{
  await mockWorkspace(page)
  await page.route('**/rpc/prmg_session_valid',route=>route.fulfill({contentType:'application/json',body:'false'}))
  await page.goto('./')
  await expect(page.getByRole('heading',{name:/Good work starts/})).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('expired')
})

test('inline tasks save in their column and preserve drafts on errors and in the full form', async ({page}) => {
  const {data, setFailSave} = await mockWorkspace(page)
  data.projects.push({id: randomUUID(), name: 'Quick tasks', status: 'active', color: '#426951', created_at: now(), updated_at: now()})
  await page.goto('./')
  await page.locator('.card-title').filter({hasText: 'Quick tasks'}).click()
  const column = page.locator('.kanban-column').filter({has: page.getByRole('heading', {name: 'In progress', exact: true})})
  await column.getByRole('button', {name: 'Add task', exact: true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const title = column.getByRole('textbox', {name: 'Title', exact: true})
  await expect(title).toBeFocused()
  await expect(column.locator('form').getByRole('button', {name: 'Add task', exact: true})).toBeDisabled()
  await title.fill('  Quick draft  ')
  setFailSave(true)
  await title.press('Enter')
  await expect(column.getByRole('alert')).toContainText('Simulated network save failure')
  await expect(title).toHaveValue('  Quick draft  ')
  setFailSave(false)
  await title.press('Enter')
  await expect(column.getByRole('button', {name: 'Quick draft', exact: true})).toBeVisible()
  expect(data.tasks).toHaveLength(1)
  expect(data.tasks[0]).toMatchObject({title: 'Quick draft', status: 'in_progress', project_id: data.projects[0].id})
  await column.getByRole('button', {name: 'Add task to In progress', exact: true}).click()
  await title.fill('More details')
  await column.getByRole('button', {name: 'Open full task form'}).click()
  await expect(page.getByRole('dialog').getByLabel('Title', {exact: true})).toHaveValue('More details')
  await expect(page.getByRole('dialog').getByRole('combobox', {name: 'Status', exact: true})).toHaveValue('in_progress')
  await expect(page.getByRole('dialog').getByRole('combobox', {name: 'Project', exact: true})).toHaveValue(data.projects[0].id)
  await page.getByRole('button', {name: 'Close dialog'}).click()
  await expect(title).toHaveCount(0)
  await column.getByRole('button', {name: 'Add task', exact: true}).click()
  await title.fill('Discard this draft')
  await column.getByRole('button', {name: 'Cancel', exact: true}).click()
  await expect(title).toHaveCount(0)
  expect(data.tasks).toHaveLength(1)
})
